"use strict";
exports.__esModule = true;
var express_1 = require("express");
var ClientFeedController = require("../controllers/ClientFeedController");
var Auth_1 = require("../middlewares/Auth");
var clientFeedRouter = express_1.Router();
clientFeedRouter.get("/", Auth_1["default"], ClientFeedController.getAll);
clientFeedRouter.post("/", Auth_1["default"], ClientFeedController.create);
clientFeedRouter.put("/:id", Auth_1["default"], ClientFeedController.update);
clientFeedRouter["delete"]("/:id", Auth_1["default"], ClientFeedController.deleteFeed);
exports["default"] = clientFeedRouter;
